# Generated by Django 5.0.6 on 2024-06-10 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
