# Generated by Django 5.0.6 on 2024-06-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
