# Generated by Django 5.0.6 on 2024-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
    ]
